# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goccc < Formula
  desc "Fast, zero-dependency CLI cost calculator and statusline for Claude Code"
  homepage "https://github.com/backstabslash/goccc"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/backstabslash/goccc/releases/download/v0.3.1/goccc_0.3.1_darwin_amd64.tar.gz"
      sha256 "1304267f136d49610639ef5fc799f200189b0b9524eb3d54623f9437a56a0621"

      define_method(:install) do
        bin.install "goccc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/backstabslash/goccc/releases/download/v0.3.1/goccc_0.3.1_darwin_arm64.tar.gz"
      sha256 "43f027303014838fe3f973a5e3cdf26c825749daf080f45b0b742e22f5071432"

      define_method(:install) do
        bin.install "goccc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/backstabslash/goccc/releases/download/v0.3.1/goccc_0.3.1_linux_amd64.tar.gz"
      sha256 "8162d491bf7b01d031457137a46e09280ebbb1a48198ab8029a970e205e05f87"
      define_method(:install) do
        bin.install "goccc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/backstabslash/goccc/releases/download/v0.3.1/goccc_0.3.1_linux_arm64.tar.gz"
      sha256 "16edf69b3d3e667f19aadb4017dac31af4aae1cc5f549427bb2d4fc8956319c8"
      define_method(:install) do
        bin.install "goccc"
      end
    end
  end

  test do
    system bin/"goccc", "-version"
  end
end
